- platform: mqtt
  name: "Test Stream"
  state_topic: "test/message"
- platform: mqtt
  name: "Fiets Credits"
  state_topic: "fiets/credits"
- platform: mqtt
  name: "Fiets TV Stand"
  state_topic: "fiets/tv"
- platform: mqtt
  name: "Fiets Aankondingen"
  state_topic: "fiets/aankondigingen"
- platform: mqtt
  name: "Fiets Automation Debug"
  state_topic: "fiets/automation-debug"
